# Copyright (c) 2020 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This workflow will install Python dependencies, run tests, lint and rat with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: C Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout SupportScripts
      uses: actions/checkout@v2
      with:
        repository: SpiNNakerManchester/SupportScripts
        path: support

    - name: Install Ubuntu packages
      uses: SpiNNakerManchester/SupportScripts/actions/apt-get-install@main
      with:
        packages: doxygen gcc-arm-none-eabi
    - name: Configure Python 3.12
      # Note: Python is needed for spinn_utilities.make_tools when building
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Checkout SpiNNaker C Dependencies
      uses: SpiNNakerManchester/SupportScripts/actions/install-spinn-deps@main
      with:
        # Note: SpiNNUtils needed for spinn_utilities.make_tools
        repositories: >
          spinnaker_tools spinn_common SpiNNFrontEndCommon sPyNNaker

    - name: "Prepare: Install SpiNNUtils"
      uses: SpiNNakerManchester/SupportScripts/actions/install-spinn-deps@main
      with:
        # Note: SpiNNUtils needed for spinn_utilities.make_tools
        repositories: SpiNNUtils
        install: true

    - name: Build SpiNNaker C code
      env:
        SPINN_INSTALL_DIR: ${{ github.workspace }}/spinnaker_tools_install
        SPINN_COMMON_INSTALL_DIR: ${{ github.workspace }}/spinn_common_install
        FEC_INSTALL_DIR: ${{ github.workspace }}/fec_install
        SPYNNAKER_INSTALL_DIR: ${{ github.workspace }}/spynnaker_install
        CFLAGS: -fdiagnostics-color=always
      run: |
        make -C spinnaker_tools install
        make -C spinn_common install
        make -C SpiNNFrontEndCommon/c_common  install
        make -C sPyNNaker/neural_modelling install

    - name: Build SpiNNaker C code globally
      env:
        CFLAGS: -fdiagnostics-color=always
      run: |
        make -C spinnaker_tools
        make -C spinn_common install
        make -C SpiNNFrontEndCommon/c_common
        make -C sPyNNaker/neural_modelling
